import { useRef, useState } from "react";
import { useSearchParams, Link } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { SupabaseClient } from "@supabase/supabase-js";
import { ArrowRight, ClipboardList, Eye, Loader2, Plus, RefreshCw } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/hooks/use-toast";
import { allRows } from "@/lib/finance";
import { assemblyRows, type AssemblyItem } from "@/lib/assembly";
import { AssemblyWorkspace } from "@/components/production/AssemblyWorkspace";
import { orderRequest } from "@/lib/sales-order";
import { PageHeader } from "@/components/shared/PageHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
type ProductionOrder = { id: string; code: string; tenant_id: string; customer_name: string | null; source_quote_id: string | null; source_order_id: string | null; due_date: string | null; notes: string | null; status: "preparing" | "released" | "completed" | "cancelled"; created_at: string };
type Database = { public: { Tables: { production_orders: { Row: ProductionOrder; Insert: Partial<ProductionOrder>; Update: Partial<ProductionOrder>; Relationships: [] } }; Views: Record<string, never>; Functions: Record<string, never>; Enums: Record<string, never>; CompositeTypes: Record<string, never> } };
const db = supabase as unknown as SupabaseClient<Database>;
type Preparation = { ready: boolean; items: { id: string; product_id: string; description: string; quantity: number; jobs: number; estimated_cost: number | null; issues: string[] }[] };
const rpc = supabase.rpc.bind(supabase) as unknown as (name: string, args: Record<string, unknown>) => PromiseLike<{ data: unknown; error: { message: string } | null }>;
const states = { preparing: "Em preparação", released: "Em produção", completed: "Concluída", cancelled: "Cancelada" };
const fmt = (value: number | null) => value == null ? "Pendente" : value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
export default function Ordens() {
  const { profile } = useAuth(); const { toast } = useToast(); const qc = useQueryClient(); const [params, setParams] = useSearchParams(); const selectedId = params.get("op");
  const [search, setSearch] = useState(""); const [status, setStatus] = useState("all"); const [creating, setCreating] = useState(false); const [source, setSource] = useState("");
  const request = useRef<{ signature: string; id: string } | null>(null);
  const orders = useQuery({ queryKey: ["production_orders", profile?.tenant_id], enabled: !!profile, queryFn: () => allRows((a, b) => db.from("production_orders").select("*").eq("tenant_id", profile!.tenant_id).order("created_at", { ascending: false }).order("id").range(a, b)) });
  const selected = orders.data?.find(row => row.id === selectedId);
  const assemblyItems = useQuery({ queryKey: ["assembly_items", selectedId], enabled: !!selectedId && selected?.status !== "preparing", queryFn: () => assemblyRows<AssemblyItem>("production_order_items", "id,product_id,description,quantity,assembled_quantity,assembly_required,production_order_id", { production_order_id: selectedId!, assembly_required: true }) });
  const sales = useQuery({ queryKey: ["production_approved_sales", profile?.tenant_id], enabled: !!profile && creating, queryFn: () => allRows((a, b) => supabase.from("orders").select("id,code").eq("tenant_id", profile!.tenant_id).eq("status", "approved").order("code").range(a, b)) });
  const preparation = useQuery({ queryKey: ["production_preflight", selectedId], enabled: !!selectedId && selected?.status === "preparing", queryFn: async () => { const r = await rpc("production_order_preflight", { p_id: selectedId }); if (r.error) throw new Error(r.error.message); return r.data as Preparation; } });
  const jobs = useQuery({ queryKey: ["production_order_jobs", selectedId], enabled: !!selectedId, queryFn: () => allRows((a, b) => supabase.from("jobs").select("id,code,name,status,planned_quantity,actual_total_cost,est_total_cost").eq("production_order_id", selectedId!).order("code").range(a, b)) });
  const refresh = async () => { await Promise.all(["production_orders", "production_preflight", "production_order_jobs", "jobs", "orders", "order_jobs", "fila_jobs"].map(key => qc.invalidateQueries({ queryKey: [key] }))); };
  const operation = useMutation({ mutationFn: async ({ action }: { action: "create" | "release" | "refresh" | "completed" | "cancelled" | "preparing" }) => {
    let result;
    if (action === "create") { if (!source) throw new Error("Selecione a venda."); request.current = orderRequest(request.current, source); result = await rpc("request_production_order", { p_quote_id: null, p_order_id: source, p_request_id: request.current.id }); }
    else if (action === "release") result = await rpc("release_production_order", { p_id: selectedId });
    else if (action === "refresh") result = await rpc("refresh_production_preparation", { p_id: selectedId });
    else result = await rpc("transition_production_order", { p_id: selectedId, p_status: action });
    if (result.error) throw new Error(result.error.message); if (!result.data) throw new Error("A operação não foi confirmada."); return { action, id: String(result.data) };
  }, onSuccess: async ({ action, id }) => { await refresh(); if (action === "create") { setCreating(false); setParams({ op: id }); } toast({ title: action === "release" ? "Produção liberada para a fila" : action === "refresh" ? "Preparação atualizada com o cadastro" : "Ordem de produção atualizada" }); }, onError: (e: Error) => toast({ title: "Não foi possível concluir", description: e.message, variant: "destructive" }) });
  const filtered = (orders.data || []).filter(row => (status === "all" || row.status === status) && `${row.code} ${row.customer_name || ""}`.toLocaleLowerCase("pt-BR").includes(search.toLocaleLowerCase("pt-BR")));
  return <div className="space-y-5"><PageHeader title="Ordens de produção" description="Do orçamento ou venda à preparação, impressão e entrega." breadcrumbs={[{ label: "Produção" }, { label: "Ordens de produção" }]} actions={<Button onClick={() => { setSource(""); setCreating(true); request.current = null; }}><Plus className="mr-2 h-4 w-4" />Adicionar ordem</Button>} />
    <div className="flex flex-wrap gap-3 rounded-lg border bg-card p-4"><Input className="min-w-52 flex-1" aria-label="Buscar ordem de produção" placeholder="Número ou cliente" value={search} onChange={e => setSearch(e.target.value)} /><select className="h-10 rounded-md border bg-background px-3 text-sm" aria-label="Situação da produção" value={status} onChange={e => setStatus(e.target.value)}><option value="all">Todas as situações</option>{Object.entries(states).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select><Button variant="outline" onClick={refresh}><RefreshCw className="mr-2 h-4 w-4" />Atualizar</Button></div>
    {orders.error ? <p role="alert" className="text-destructive">{orders.error.message}</p> : orders.isLoading ? <p>Carregando…</p> : <div className="overflow-x-auto rounded-lg border bg-card"><table className="w-full text-left text-sm"><thead className="border-b bg-muted/40"><tr>{["Número", "Cliente", "Entrega", "Situação", "Origem", "Ações"].map(label => <th className="p-3 font-medium" key={label}>{label}</th>)}</tr></thead><tbody>{filtered.map(row => <tr className="border-b last:border-0" key={row.id}><td className="p-3 font-medium">{row.code}</td><td className="p-3">{row.customer_name || "—"}</td><td className="p-3">{row.due_date ? new Date(row.due_date + "T12:00:00").toLocaleDateString("pt-BR") : "A definir"}</td><td className="p-3">{states[row.status]}</td><td className="p-3">{row.source_order_id ? "Venda" : "Orçamento"}</td><td className="p-2"><Button variant="ghost" onClick={() => setParams({ op: row.id })}><Eye className="mr-2 h-4 w-4" />Abrir</Button></td></tr>)}{!filtered.length && <tr><td colSpan={6} className="p-10 text-center text-muted-foreground"><ClipboardList className="mx-auto mb-3 h-8 w-8" />Gere uma OP pelo orçamento aprovado ou por uma venda.</td></tr>}</tbody></table></div>}
    <Dialog open={!!selectedId} onOpenChange={open => { if (!open && !operation.isPending) setParams({}); }}><DialogContent className="flex h-[92dvh] w-[96vw] max-w-5xl flex-col gap-0 overflow-hidden p-0"><DialogHeader className="border-b p-5 pr-12"><DialogTitle>{selected?.code || "Ordem de produção"}</DialogTitle><DialogDescription>{selected?.customer_name || "Carregando"} · {selected ? states[selected.status] : ""}</DialogDescription></DialogHeader><div className="min-h-0 flex-1 space-y-5 overflow-y-auto p-5">
      {selected?.source_order_id ? <Button variant="outline" asChild><Link to={`/comercial/pedidos?pedido=${selected.source_order_id}`}>Abrir venda vinculada<ArrowRight className="ml-2 h-4 w-4" /></Link></Button> : <p className="rounded-lg border bg-muted/30 p-3 text-sm">Origem: orçamento aprovado. Esta OP não gerou uma conta a receber.</p>}
      {selected?.status === "preparing" && <><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Preparação dos produtos</h2><Button variant="outline" disabled={operation.isPending || preparation.isFetching} onClick={() => operation.mutate({ action: "refresh" })}><RefreshCw className="mr-2 h-4 w-4" />Atualizar composição da OP</Button></div><p className="text-sm text-muted-foreground">Confira a composição técnica antes de liberar. Atualizar usa os arquivos, tempos e materiais atuais do cadastro, mantendo as escolhas de material do item. Os preços e a proposta comercial permanecem preservados.</p>{preparation.isFetching ? <p>Conferindo a preparação…</p> : preparation.error ? <p role="alert" className="text-destructive">{preparation.error.message}</p> : preparation.data?.items.map(item => <article className="rounded-lg border p-4" key={item.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-medium">{item.description}</h3><p className="text-sm text-muted-foreground">{item.quantity} unidades · {item.jobs} impressões · custo previsto {fmt(item.estimated_cost)}</p></div><Button variant="outline" size="sm" asChild><Link to={`/comercial/produtos?produto=${item.product_id}`}>Preparar produto</Link></Button></div>{item.issues.length > 0 ? <ul className="mt-3 list-inside list-disc text-sm text-amber-800">{item.issues.map((issue, i) => <li key={i}>{issue}</li>)}</ul> : <p className="mt-3 text-sm text-emerald-700">Composição e tempo preparados para gerar a fila.</p>}</article>)}</>}
      {(jobs.data?.length || 0) > 0 && <section><h2 className="mb-3 font-semibold">Impressões vinculadas</h2><div className="overflow-x-auto rounded-lg border"><table className="w-full text-left text-sm"><thead className="bg-muted/40"><tr><th className="p-3">Impressão</th><th className="p-3">Produto</th><th className="p-3">Peças no lote</th><th className="p-3">Situação</th></tr></thead><tbody>{jobs.data?.map(job => <tr className="border-t" key={job.id}><td className="p-3">{job.code}</td><td className="p-3">{job.name}</td><td className="p-3">{job.planned_quantity}</td><td className="p-3">{({ draft: "Rascunho", queued: "Na fila", printing: "Imprimindo", paused: "Pausada", failed: "Falhou", reprint: "Reimpressão", post_processing: "Acabamento", quality_check: "Qualidade", ready: "Pronta", shipped: "Enviada", completed: "Concluída" })[job.status]}</td></tr>)}</tbody></table></div><Button asChild variant="outline" className="mt-3"><Link to={`/producao/jobs?op=${selectedId}`}>Acompanhar impressões<ArrowRight className="ml-2 h-4 w-4" /></Link></Button></section>}
      {profile && assemblyItems.data?.map(item => <div className="rounded-lg border p-4" key={item.id}><AssemblyWorkspace productId={item.product_id} tenantId={profile.tenant_id} itemId={item.id} /></div>)}
      {assemblyItems.error && <p role="alert" className="text-destructive">{assemblyItems.error.message}</p>}
      {selected?.notes && <p className="whitespace-pre-wrap rounded-lg border p-4 text-sm">{selected.notes}</p>}{jobs.error && <p role="alert" className="text-destructive">{jobs.error.message}</p>}
    </div><DialogFooter className="flex-row flex-wrap justify-between gap-2 border-t p-4"><Button variant="outline" onClick={() => setParams({})} disabled={operation.isPending}>Fechar</Button>{selected?.status === "preparing" && <><Button variant="ghost" disabled={operation.isPending} onClick={() => operation.mutate({ action: "cancelled" })}>Cancelar OP</Button><Button disabled={operation.isPending || preparation.isFetching || !preparation.data?.ready} onClick={() => operation.mutate({ action: "release" })}>{operation.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Liberar para a fila</Button></>}{selected?.status === "cancelled" && <Button disabled={operation.isPending} onClick={() => operation.mutate({ action: "preparing" })}>Reabrir preparação</Button>}{selected?.status === "released" && <Button disabled={operation.isPending} onClick={() => operation.mutate({ action: "completed" })}>Concluir produção</Button>}</DialogFooter></DialogContent></Dialog>
    <Dialog open={creating} onOpenChange={open => { if (!operation.isPending) setCreating(open); }}><DialogContent><DialogHeader><DialogTitle>Adicionar ordem de produção</DialogTitle><DialogDescription>Selecione uma venda aprovada. Para produzir a partir de um orçamento, use Gerar OP no orçamento.</DialogDescription></DialogHeader><Label htmlFor="op-sale">Venda</Label><select id="op-sale" className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={source} onChange={e => setSource(e.target.value)}><option value="">Selecione</option>{sales.data?.map(sale => <option key={sale.id} value={sale.id}>{sale.code}</option>)}</select>{sales.error && <p role="alert">{sales.error.message}</p>}<DialogFooter><Button variant="outline" asChild><Link to="/comercial/orcamentos">Abrir orçamentos</Link></Button><Button disabled={operation.isPending || !source} onClick={() => operation.mutate({ action: "create" })}>Gerar ordem</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
