import { useRef, useState } from "react";
import { Link } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Loader2, PackageCheck, Printer, RefreshCw } from "lucide-react";
import { assemblyKeys, assemblyRows, assemblyRpc, readAssemblyStatus, type AssemblyComponent, type AssemblyHistory, type ComponentJob } from "@/lib/assembly";
import { orderRequest } from "@/lib/sales-order";
import { positiveInteger } from "@/lib/production";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";

type Action = { kind: "batch" | "entry" | "loss"; part: AssemblyComponent } | { kind: "assemble" } | { kind: "quality"; job: ComponentJob };
const currency = (n: number) => n.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
export function AssemblyWorkspace({ productId, tenantId, itemId }: { productId: string; tenantId: string; itemId?: string }) {
  const qc = useQueryClient(); const { toast } = useToast(); const [target, setTarget] = useState("10");
  const [action, setAction] = useState<Action | null>(null); const [quantity, setQuantity] = useState("1"); const [cost, setCost] = useState("0"); const [notes, setNotes] = useState("");
  const request = useRef<{ signature: string; id: string } | null>(null);
  const targetNumber = Number(target); const validTarget = Number.isInteger(targetNumber) && targetNumber > 0 && targetNumber <= 10000;
  const status = useQuery({ queryKey: ["assembly_status", tenantId, productId, itemId, targetNumber], enabled: validTarget, refetchInterval: 15000, queryFn: () => readAssemblyStatus(productId, targetNumber, itemId) });
  const jobs = useQuery({ queryKey: ["assembly_jobs", tenantId, productId], refetchInterval: 15000, queryFn: () => assemblyRows<ComponentJob>("jobs", "id,code,name,description,planned_quantity,produced_quantity,component_stock_key,status", { tenant_id: tenantId, product_id: productId, status: "quality_check" }) });
  const history = useQuery({ queryKey: ["assembly_history", tenantId, productId], queryFn: () => assemblyRows<AssemblyHistory>("product_assemblies", "id,quantity,component_cost,finishing_cost,item_id,created_at,notes", { tenant_id: tenantId, product_id: productId }, "created_at") });
  const refresh = () => Promise.all(assemblyKeys.map(key => qc.invalidateQueries({ queryKey: [key] })));
  const open = (next: Action) => { setAction(next); setQuantity(next.kind === "batch" ? String(Math.max(1, next.part.to_print || next.part.missing)) : next.kind === "quality" ? String(next.job.produced_quantity ?? next.job.planned_quantity) : next.kind === "assemble" ? String(Math.max(1, Math.min(status.data?.ready_to_assemble || 1, status.data?.required || 1))) : "1"); setCost("0"); setNotes(""); request.current = null; };
  const save = useMutation({ mutationFn: async () => {
    if (!action) throw new Error("Selecione a operação.");
    const qty = action.kind === "quality" && quantity === "0" ? 0 : positiveInteger(quantity, "Quantidade", 10000);
    const money = Number(cost.replace(",", ".")); if (!Number.isFinite(money) || money < 0) throw new Error("Informe um custo válido.");
    const signature = JSON.stringify([productId, itemId, action, qty, money, notes]); request.current = orderRequest(request.current, signature);
    const shared = { p_request_id: request.current.id };
    if (action.kind === "batch") return assemblyRpc<string[]>("plan_component_batch", { ...shared, p_plate_id: action.part.plate_id, p_quantity: qty, p_item_id: itemId || null });
    if (action.kind === "loss") return assemblyRpc<string>("write_off_components", { ...shared, p_plate_id: action.part.plate_id, p_quantity: qty, p_notes: notes, p_item_id: itemId || null });
    if (action.kind === "entry") return assemblyRpc<string>("receive_existing_components", { ...shared, p_plate_id: action.part.plate_id, p_quantity: qty, p_unit_cost: money, p_notes: notes });
    if (action.kind === "quality") return assemblyRpc<string>("confirm_component_output", { ...shared, p_job_id: action.job.id, p_good_quantity: qty, p_reason: notes });
    return assemblyRpc<string>("assemble_product", { ...shared, p_product_id: productId, p_quantity: qty, p_item_id: itemId || null, p_finishing_cost: money, p_notes: notes });
  }, onSuccess: async () => { const kind = action?.kind; setAction(null); await refresh(); toast({ title: kind === "batch" ? "Lote enviado à fila de impressão" : kind === "assemble" ? "Montagem registrada" : "Saldo de componentes atualizado" }); }, onError: (e: Error) => toast({ title: "Não foi possível concluir", description: e.message, variant: "destructive" }) });
  const data = status.data; const goodJobs = jobs.data?.filter(job => job.component_stock_key && data?.components.some(part => part.material_key === job.component_stock_key)) || [];
  return <section className="space-y-4" aria-label="Componentes e montagem">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-semibold">{data?.name || "Componentes e montagem"}</h2><p className="text-sm text-muted-foreground">Cada componente representa o conjunto de peças necessário para um produto: por exemplo, o par de metades do corpo, um caule e uma folha.</p></div><Button variant="outline" size="sm" onClick={refresh}><RefreshCw className="mr-2 h-4 w-4" />Atualizar saldos</Button></div>
    {!itemId && <div className="flex flex-wrap items-end gap-3"><div><Label htmlFor={`assembly-target-${productId}`}>Quantos produtos quero montar?</Label><Input id={`assembly-target-${productId}`} className="w-40" type="number" min={1} max={10000} value={target} onChange={e => setTarget(e.target.value)} /></div><Button variant="outline" asChild><Link to={`/comercial/produtos?produto=${productId}`}>Editar componentes do produto</Link></Button></div>}
    {!validTarget && <p role="alert" className="text-destructive">Informe de 1 a 10000 produtos.</p>}
    {status.error && <p role="alert" className="text-destructive">{status.error.message}</p>}
    {status.isLoading ? <p>Conferindo componentes…</p> : data && <>
      {!data.enabled && <p className="rounded-lg border bg-amber-50 p-4 text-sm text-amber-900">Ative o controle de montagem na aba Composição / produção do produto.</p>}
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-3"><article className="rounded-lg border bg-emerald-50 p-4 text-emerald-950"><p className="text-sm">Podem ser montados agora</p><strong className="text-3xl">{itemId ? Math.min(data.required, data.ready_to_assemble) : data.ready_to_assemble}</strong><p className="text-xs">Com todas as partes conferidas e disponíveis.</p></article><article className="rounded-lg border bg-card p-4"><p className="text-sm">{itemId ? "Já montados nesta OP" : "Produtos prontos em estoque"}</p><strong className="text-3xl">{itemId ? data.assembled : data.finished_stock}</strong><p className="text-xs text-muted-foreground">{itemId ? "Destinados a esta ordem de produção." : "Após montagem, termoformagem e acabamento."}</p></article><article className="rounded-lg border bg-card p-4"><p className="text-sm">Ainda faltam para a meta</p><strong className="text-3xl">{Math.max(0, data.required - data.ready_to_assemble)}</strong><p className="text-xs text-muted-foreground">A tabela indica o componente que está faltando.</p></article></div>
      <div className="overflow-x-auto rounded-lg border"><table className="w-full text-left text-sm"><thead className="bg-muted/40"><tr>{["Componente", "Por impressão", "Em estoque", "Disponível", "Na fila / conferência", "Falta para a meta", "Ações"].map(label => <th className="whitespace-nowrap p-3" key={label}>{label}</th>)}</tr></thead><tbody>{data.components.map(part => <tr className="border-t" key={part.plate_id}><td className="min-w-36 p-3 font-medium">{part.label}<p className="text-xs font-normal text-muted-foreground">Placa {part.plate_index}{!part.prepared && " · preparar materiais"}</p></td><td className="p-3">{part.units_per_print ?? "A definir"}</td><td className="p-3">{part.balance}</td><td className="p-3">{part.available}{part.reserved > 0 && <p className="whitespace-nowrap text-xs text-muted-foreground">{part.reserved} reservado(s)</p>}</td><td className="p-3">{part.pending}</td><td className={`p-3 ${part.missing ? "font-semibold text-amber-800" : "text-emerald-700"}`}>{part.missing ? <>{part.missing} para montar<p className="mt-1 text-xs font-normal">{part.to_print > 0 ? `${part.to_print} a imprimir · ${part.runs ?? "?"} lote(s)` : "Fila cobre a falta"}</p></> : "Atendido"}</td><td className="p-2"><div className="flex flex-col items-start gap-1"><Button variant="outline" size="sm" disabled={!data.enabled || !part.prepared || save.isPending} onClick={() => open({ kind: "batch", part })}><Printer className="mr-2 h-4 w-4" />Produzir lote</Button>{!itemId && <Button variant="ghost" size="sm" disabled={!data.enabled || !part.prepared || save.isPending} onClick={() => open({ kind: "entry", part })}>Registrar peças existentes</Button>}<Button variant="ghost" size="sm" disabled={!part.available || save.isPending} onClick={() => open({ kind: "loss", part })}>Registrar perda</Button></div></td></tr>)}</tbody></table></div>
      <p className="text-xs text-muted-foreground">Saldos separados por componente e material/cor. Peças na fila ainda não são estoque disponível. Ordens liberadas reservam os componentes por ordem de liberação; sobras ficam para as próximas montagens.</p>
      <div className="flex flex-wrap items-center gap-3"><Button disabled={!data.enabled || !data.ready_to_assemble || (itemId && !data.required) || save.isPending || status.isFetching} onClick={() => open({ kind: "assemble" })}><PackageCheck className="mr-2 h-4 w-4" />Registrar montagem / acabamento</Button><Button variant="outline" asChild><Link to="/producao/jobs">Acompanhar impressões</Link></Button></div>
      {goodJobs.length > 0 && <div className="space-y-2 rounded-lg border p-4"><h3 className="font-semibold">Lotes aguardando conferência</h3>{goodJobs.map(job => <div className="flex flex-wrap items-center justify-between gap-2 border-t pt-2 text-sm" key={job.id}><span>{job.code} · {job.name} · lote de {job.planned_quantity}</span><Button size="sm" variant="outline" onClick={() => open({ kind: "quality", job })}>Conferir {job.code}</Button></div>)}</div>}
    </>}
    {jobs.error && <p role="alert" className="text-destructive">{jobs.error.message}</p>}
    <details className="rounded-lg border p-4"><summary className="cursor-pointer font-medium">Histórico de montagem</summary>{history.error ? <p role="alert">{history.error.message}</p> : <ul className="mt-3 space-y-2 text-sm">{history.data?.filter(row => !itemId || row.item_id === itemId).slice().reverse().map(row => <li key={row.id} className="border-t pt-2">{new Date(row.created_at).toLocaleString("pt-BR")} · {row.quantity} produto(s) · {row.item_id ? "Destinados à OP" : "Entrada em estoque"} · custo {currency(Number(row.component_cost) + Number(row.finishing_cost))}{row.notes && <p className="text-muted-foreground">{row.notes}</p>}</li>)}{!history.data?.length && <li>Nenhuma montagem registrada.</li>}</ul>}</details>
    <Dialog open={!!action} onOpenChange={open => { if (!open && !save.isPending) setAction(null); }}><DialogContent className="max-h-[90dvh] overflow-y-auto" closeDisabled={save.isPending}><DialogHeader><DialogTitle>{action?.kind === "batch" ? `Produzir ${action.part.label}` : action?.kind === "entry" ? `Entrada de ${action.part.label}` : action?.kind === "loss" ? `Perda de ${action.part.label}` : action?.kind === "quality" ? `Conferir ${action.job.code}` : "Concluir montagem / acabamento"}</DialogTitle><DialogDescription>{action?.kind === "batch" ? "Produza este componente em lote próprio. As outras placas não serão enviadas à fila." : action?.kind === "entry" ? "Registre peças que já existem fisicamente, com os materiais e cores atuais do cadastro." : action?.kind === "loss" ? "Baixe componentes danificados no estoque, na termoformagem ou na montagem. A quantidade faltante será recalculada." : action?.kind === "quality" ? "Informe quantos conjuntos saíram bons. Somente a quantidade aprovada entra no saldo." : itemId ? "Confirme os produtos montados, incluindo termoformagem e acabamento. Eles ficam destinados a esta OP." : "Confirme os produtos montados, incluindo termoformagem e acabamento. A operação baixa os componentes e dá entrada no estoque do produto pronto."}</DialogDescription></DialogHeader>
      <div><Label htmlFor="assembly-quantity">{action?.kind === "quality" ? "Quantidade boa" : "Quantidade"}</Label><Input id="assembly-quantity" type="number" min={action?.kind === "quality" ? 0 : 1} step={1} value={quantity} onChange={e => setQuantity(e.target.value)} /></div>
      {action?.kind === "batch" && action.part.units_per_print && Number(quantity) > 0 && <p className="rounded-lg bg-muted p-3 text-sm">{Math.ceil(Number(quantity) / action.part.units_per_print)} impressão(ões) × {action.part.units_per_print} conjuntos = {Math.ceil(Number(quantity) / action.part.units_per_print) * action.part.units_per_print} conjuntos previstos. As sobras ficam disponíveis para outras montagens.</p>}
      {(action?.kind === "entry" || action?.kind === "assemble") && <div><Label htmlFor="assembly-cost">{action.kind === "entry" ? "Custo por conjunto do componente (R$)" : "Custo adicional total de montagem / acabamento (R$)"}</Label><Input id="assembly-cost" inputMode="decimal" value={cost} onChange={e => setCost(e.target.value)} /></div>}
      {action?.kind !== "batch" && <div><Label htmlFor="assembly-notes">{action?.kind === "loss" ? "Motivo da perda *" : action?.kind === "entry" ? "Motivo da entrada *" : action?.kind === "quality" ? "Motivo das rejeições (se houver)" : "Observações"}</Label><Input id="assembly-notes" value={notes} onChange={e => setNotes(e.target.value)} /></div>}
      <DialogFooter><Button variant="outline" disabled={save.isPending} onClick={() => setAction(null)}>Cancelar</Button><Button disabled={save.isPending} onClick={() => save.mutate()}>{save.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}{action?.kind === "batch" ? "Criar lote de impressão" : action?.kind === "assemble" ? "Confirmar produtos montados" : "Confirmar quantidade"}</Button></DialogFooter>
    </DialogContent></Dialog>
  </section>;
}
