import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { AlertTriangle, ArrowDownLeft, ArrowRight, ArrowUpRight, Box, ChartNoAxesCombined, CheckCircle2, Circle, Package, Printer, RefreshCw, ShoppingCart, Wallet } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { PageHeader } from "@/components/shared/PageHeader";
import { Button } from "@/components/ui/button";
import { KpiCard } from "@/components/KpiCard";
import { useAuth } from "@/contexts/AuthContext";
import { supabase } from "@/integrations/supabase/client";
import { collectDashboardRows, numberValue, summarizeDashboard } from "@/lib/dashboard-metrics";
import { cn } from "@/lib/utils";

const currency = (value: number) => value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const labels: Record<string, string> = { draft: "Rascunho", queued: "Na fila", printing: "Imprimindo", paused: "Pausado", failed: "Falha", reprint: "Reimpressão", post_processing: "Acabamento", quality_check: "Inspeção", ready: "Pronto", shipped: "Enviado", completed: "Concluído", idle: "Disponível", offline: "Offline", error: "Erro", maintenance: "Manutenção" };

function PanelHeading({ title, description, href, link = "Ver todos" }: { title: string; description?: string; href?: string; link?: string }) {
  return <div className="flex flex-wrap items-start justify-between gap-3 border-b border-border px-5 py-4"><div><h2 className="text-sm font-semibold">{title}</h2>{description && <p className="mt-1 text-xs text-muted-foreground">{description}</p>}</div>{href && <Link className="inline-flex min-h-8 items-center gap-1 text-xs font-medium text-primary hover:underline" to={href}>{link}<ArrowRight className="h-3.5 w-3.5" /></Link>}</div>;
}
function Empty({ icon: Icon = Package, title, description }: { icon?: typeof Package; title: string; description: string }) {
  return <div className="flex min-h-40 flex-col items-center justify-center px-6 py-8 text-center"><Icon className="mb-3 h-7 w-7 text-muted-foreground/50" /><p className="text-sm font-medium">{title}</p><p className="mt-1 max-w-xs text-xs leading-relaxed text-muted-foreground">{description}</p></div>;
}

export default function Dashboard() {
  const { profile } = useAuth();
  const tenantId = profile?.tenant_id;
  const { data, isPending, isFetching, error, refetch, dataUpdatedAt } = useQuery({
    queryKey: ["dashboard", tenantId], enabled: !!tenantId, staleTime: 30_000, retry: 1,
    queryFn: async () => {
      const [jobs, payables, receivables, inventory, banks, orders, printers] = await Promise.all([
        collectDashboardRows((from, to) => supabase.from("jobs").select("id, code, name, status, sale_price, actual_total_cost, est_total_cost, completed_at, est_time_minutes, created_at, printers(name)").eq("tenant_id", tenantId!).order("created_at", { ascending: false }).order("id").range(from, to)),
        collectDashboardRows((from, to) => supabase.from("accounts_payable").select("id, description, amount, amount_paid, due_date, status").eq("tenant_id", tenantId!).in("status", ["open", "partial", "overdue"]).order("id").range(from, to)),
        collectDashboardRows((from, to) => supabase.from("accounts_receivable").select("id, description, amount, amount_received, due_date, status").eq("tenant_id", tenantId!).in("status", ["open", "partial", "overdue"]).order("id").range(from, to)),
        collectDashboardRows((from, to) => supabase.from("inventory_items").select("id, name, current_stock, min_stock, unit").eq("tenant_id", tenantId!).eq("is_active", true).order("id").range(from, to)),
        collectDashboardRows((from, to) => supabase.from("bank_accounts").select("id, current_balance").eq("tenant_id", tenantId!).eq("is_active", true).order("id").range(from, to)),
        collectDashboardRows((from, to) => supabase.from("orders").select("id, status").eq("tenant_id", tenantId!).neq("status", "cancelled").order("id").range(from, to)),
        collectDashboardRows((from, to) => supabase.from("printers").select("id, name, model, status").eq("tenant_id", tenantId!).eq("is_active", true).order("id").range(from, to)),
      ]);
      return { jobs, orders, printers, inventory, bankCount: banks.length, cash: banks.reduce((sum, bank) => sum + numberValue(bank.current_balance), 0), stockAlerts: inventory.filter(item => item.min_stock != null && numberValue(item.current_stock) < numberValue(item.min_stock)), ...summarizeDashboard(jobs, payables, receivables) };
    },
  });
  return <div className="space-y-6 page-enter">
    <PageHeader title="Visão geral" description="Financeiro, pedidos e produção em um só lugar." actions={<Button variant="outline" disabled={isFetching} onClick={() => void refetch()}><RefreshCw className={cn("mr-2 h-4 w-4", isFetching && "animate-spin")} />{isFetching ? "Atualizando" : "Atualizar"}</Button>} />
    {error && <div role="alert" className="flex items-start gap-3 rounded-xl border border-destructive/25 bg-destructive/5 p-4"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-destructive" /><div><p className="text-sm font-semibold">Não foi possível atualizar os indicadores.</p><p className="mt-1 text-sm text-muted-foreground">{data ? "Os dados abaixo correspondem à última atualização concluída." : "Tente novamente para consultar os dados da operação."}</p><Button variant="link" className="h-9 px-0" onClick={() => void refetch()}>Tentar novamente</Button></div></div>}
    {isPending && !error && <div role="status" aria-label="Carregando indicadores" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[1, 2, 3, 4].map(value => <div key={value} className="h-36 animate-pulse rounded-xl border bg-card" />)}<span className="sr-only">Carregando dados da operação...</span></div>}
    {data && <>
      <div className="flex flex-wrap items-center justify-between gap-3"><p className="flex items-center gap-2 text-xs text-muted-foreground"><span className="h-1.5 w-1.5 rounded-full bg-success" />Atualizado às {new Date(dataUpdatedAt).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}</p><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" asChild><Link to="/comercial/pedidos"><ShoppingCart className="mr-2 h-4 w-4" />Pedidos</Link></Button><Button size="sm" asChild><Link to="/producao/jobs"><Printer className="mr-2 h-4 w-4" />Produção<ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div></div>
      <div className="grid grid-cols-2 gap-3 sm:gap-4 xl:grid-cols-4">
        <KpiCard label="Saldo disponível" value={currency(data.cash)} icon={<Wallet className="h-4 w-4" />} subvalue={`${data.bankCount} conta(s) ativa(s)`} />
        <KpiCard label="A receber" value={currency(data.receivableTotal)} icon={<ArrowDownLeft className="h-4 w-4" />} subvalue={`${data.overdueReceivableCount} título(s) em atraso · saldo em aberto`} />
        <KpiCard label="A pagar" value={currency(data.payableTotal)} icon={<ArrowUpRight className="h-4 w-4" />} subvalue={`${data.overduePayableCount} título(s) em atraso · saldo em aberto`} />
        <KpiCard label="Jobs em andamento" value={String(data.activeJobs.length)} icon={<Printer className="h-4 w-4" />} subvalue={`${data.jobs.filter(job => job.status === "printing").length} imprimindo · ${data.jobs.filter(job => job.status === "queued").length} na fila`} />
      </div>
      {(data.overduePayableCount > 0 || data.stockAlerts.length > 0 || data.overdueReceivableCount > 0) && <div className="grid gap-3 md:grid-cols-3">{[
        { count: data.overduePayableCount, label: "conta(s) a pagar vencida(s)", href: "/financeiro/pagar" },
        { count: data.overdueReceivableCount, label: "recebimento(s) em atraso", href: "/financeiro/receber" },
        { count: data.stockAlerts.length, label: "material(is) abaixo do mínimo", href: "/estoque/alertas" },
      ].filter(alert => alert.count > 0).map(alert => <Link key={alert.href} to={alert.href} className="flex min-h-14 items-center gap-3 rounded-lg border border-warning/25 bg-warning/5 px-4 py-3 text-sm hover:bg-warning/10"><AlertTriangle className="h-4 w-4 shrink-0 text-amber-700" /><span className="flex-1"><strong>{alert.count}</strong> {alert.label}</span><ArrowRight className="h-4 w-4 text-muted-foreground" /></Link>)}</div>}
      <div className="grid gap-5 xl:grid-cols-[minmax(0,1.7fr)_minmax(0,1fr)]">
        <section className="min-w-0 overflow-hidden rounded-xl border bg-card"><PanelHeading title="Resultado de produção" description="Valor dos jobs concluídos e custos de produção, incluindo falhas, nos últimos 6 meses." href="/producao/margem" link="Analisar margens" />
          <div className="flex flex-wrap gap-x-6 gap-y-2 px-5 pt-4 text-xs text-muted-foreground"><span className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-primary" />Valor dos jobs</span><span className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-amber-600" />Custo de produção</span></div>
          <div className="h-64 px-2 pb-3 pt-4 sm:px-4">{data.months.some(month => month.value || month.cost) ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={data.months} margin={{ top: 10, right: 15, left: 0, bottom: 0 }}><defs><linearGradient id="production-value" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="hsl(var(--primary))" stopOpacity={0.18} /><stop offset="100%" stopColor="hsl(var(--primary))" stopOpacity={0} /></linearGradient></defs><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="hsl(var(--border))" /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fontSize: 11 }} dy={8} /><YAxis width={58} axisLine={false} tickLine={false} tick={{ fontSize: 10 }} tickFormatter={value => Number(value).toLocaleString("pt-BR", { notation: "compact" })} /><Tooltip formatter={(value: number, name: string) => [currency(value), name === "value" ? "Valor dos jobs" : "Custo"]} contentStyle={{ borderRadius: 10, borderColor: "hsl(var(--border))", fontSize: 12 }} /><Area type="monotone" dataKey="value" stroke="hsl(var(--primary))" fill="url(#production-value)" strokeWidth={2.5} /><Area type="monotone" dataKey="cost" stroke="#b7791f" fill="transparent" strokeWidth={2} /></AreaChart></ResponsiveContainer> : <Empty icon={ChartNoAxesCombined} title="Sem produção concluída no período" description="O gráfico será preenchido com jobs concluídos que tenham preço e custo informados." />}</div>
          <p className="border-t bg-muted/25 px-5 py-3 text-xs leading-relaxed text-muted-foreground">Custos estimados são usados quando o custo real não foi informado. Este gráfico acompanha a produção; consulte a DRE para o resultado financeiro.</p>
        </section>
        <section className="min-w-0 overflow-hidden rounded-xl border bg-card"><PanelHeading title="Saúde da operação" description="Histórico completo de jobs locais." />
          <div className="space-y-5 p-5"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-medium">Margem de produção</p><p className="mt-1 text-xs text-muted-foreground">Jobs apurados, incluindo o custo das tentativas com falha</p></div><strong className="text-xl tabular-nums">{data.productionMargin == null ? "—" : `${data.productionMargin.toFixed(1)}%`}</strong></div><div className="flex items-center justify-between gap-4 border-t pt-4"><div><p className="text-sm font-medium">Jobs com falha</p><p className="mt-1 text-xs text-muted-foreground">{data.failedCount} falha(s) · {data.completedCount} concluído(s)</p></div><strong className={cn("text-xl tabular-nums", data.failedCount > 0 && "text-destructive")}>{data.lossRate == null ? "—" : `${data.lossRate.toFixed(1)}%`}</strong></div><div className="rounded-lg bg-muted/60 p-3 text-xs leading-relaxed text-muted-foreground">{data.estimatedCostCount > 0 ? `${data.estimatedCostCount} job(s) com custo estimado. ` : ""}{data.missingCostCount > 0 ? `${data.missingCostCount} job(s) sem preço ou custo completo, fora da margem. ` : ""}A margem de produção não inclui despesas administrativas, tributos ou taxas de venda.</div><Button variant="outline" className="w-full" asChild><Link to="/financeiro/dre">Abrir demonstrativo financeiro<ArrowRight className="ml-auto h-4 w-4" /></Link></Button></div>
        </section>
      </div>
      <section className="overflow-hidden rounded-xl border bg-card"><PanelHeading title="Pedidos em operação" href="/comercial/pedidos" /><div className="grid grid-cols-2 divide-border sm:grid-cols-5">{[{ key: "draft", label: "Rascunhos" }, { key: "approved", label: "Aprovados" }, { key: "in_production", label: "Em produção" }, { key: "ready", label: "Prontos" }, { key: "shipped", label: "Enviados" }].map(stage => <Link to="/comercial/pedidos" key={stage.key} className="flex items-center justify-between gap-3 border-b border-r px-5 py-4 transition-colors hover:bg-muted/50"><span className="text-xs text-muted-foreground">{stage.label}</span><strong className="text-xl tabular-nums">{data.orders.filter(order => order.status === stage.key).length}</strong></Link>)}</div></section>
      <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1.7fr)_minmax(0,1fr)]">
        <div className="min-w-0 space-y-5"><section className="overflow-hidden rounded-xl border bg-card"><PanelHeading title="Produção recente" description="Últimos 8 jobs cadastrados." href="/producao/jobs" />{data.jobs.length === 0 ? <Empty icon={Printer} title="Sua produção começa aqui" description="Cadastre um job para acompanhar material, tempo, custo e andamento da impressão." /> : <div className="divide-y">{data.jobs.slice(0, 8).map(job => <Link key={job.id} to="/producao/jobs" className="flex min-h-20 items-center gap-3 px-5 py-4 hover:bg-muted/40"><span className="hidden h-10 w-10 shrink-0 items-center justify-center rounded-lg border bg-muted/40 sm:flex"><Box className="h-4 w-4 text-muted-foreground" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{job.name}</p><p className="mt-1 truncate text-xs text-muted-foreground">{job.code} · {job.printers?.name ?? "Impressora não definida"}</p></div><span className={cn("shrink-0 rounded-full border px-2.5 py-1 text-[11px] font-medium", job.status === "printing" ? "border-primary/20 bg-primary/5 text-primary" : job.status === "failed" ? "border-destructive/20 bg-destructive/5 text-destructive" : "bg-muted/40 text-muted-foreground")}>{labels[job.status] ?? job.status}</span><ArrowRight className="hidden h-4 w-4 text-muted-foreground sm:block" /></Link>)}</div>}</section>
          <section className="overflow-hidden rounded-xl border bg-card"><PanelHeading title="Impressoras" description="Status registrado no cadastro. Telemetria detalhada na integração Bambu Lab." href="/producao/impressoras" link="Gerenciar" />{data.printers.length === 0 ? <Empty icon={Printer} title="Nenhuma impressora cadastrada" description="Cadastre suas máquinas para organizar a capacidade de produção." /> : <div className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-3">{data.printers.map(printer => <Link key={printer.id} to="/producao/impressoras" className="min-w-0 rounded-lg border p-3 hover:border-primary/30"><p className="flex items-center gap-2 truncate text-sm font-medium"><Circle className={cn("h-2 w-2 shrink-0 fill-current", printer.status === "printing" ? "text-success" : printer.status === "error" ? "text-destructive" : "text-muted-foreground")} />{printer.name}</p><p className="mt-2 truncate text-xs text-muted-foreground">{printer.model || "Modelo não informado"}</p><p className="mt-1 text-xs text-muted-foreground">{labels[printer.status] ?? printer.status}</p></Link>)}</div>}</section></div>
        <div className="min-w-0 space-y-5"><section className="overflow-hidden rounded-xl border bg-card"><PanelHeading title="Próximos pagamentos" description="Saldo pendente, descontando pagamentos parciais." href="/financeiro/pagar" />{data.pendingPayables.length === 0 ? <Empty icon={CheckCircle2} title="Nenhum pagamento em aberto" description="Novas contas a pagar aparecerão aqui, em ordem de vencimento." /> : <div className="divide-y">{data.pendingPayables.slice(0, 5).map(title => <Link to="/financeiro/pagar" key={title.id} className="flex items-center gap-3 px-5 py-4 hover:bg-muted/40"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{title.description}</p><p className={cn("mt-1 text-xs", title.overdue ? "text-destructive" : "text-muted-foreground")}>{title.overdue ? "Vencido em " : "Vence em "}{new Date(`${title.due_date}T12:00:00`).toLocaleDateString("pt-BR")}</p></div><strong className="shrink-0 text-sm tabular-nums">{currency(title.remaining)}</strong></Link>)}</div>}</section>
          <section className="overflow-hidden rounded-xl border bg-card"><PanelHeading title="Reposição de materiais" href="/estoque/alertas" />{data.stockAlerts.length === 0 ? <Empty icon={Package} title={data.inventory.length ? "Sem alertas de reposição" : "Nenhum material cadastrado"} description={data.inventory.length ? "Os materiais estão dentro dos mínimos configurados." : "Cadastre materiais e limites de estoque para acompanhar a reposição."} /> : <div className="divide-y">{data.stockAlerts.slice(0, 5).map(item => <Link to="/estoque/alertas" key={item.id} className="flex items-center gap-3 px-5 py-4 hover:bg-muted/40"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{item.name}</p><p className="mt-1 text-xs text-muted-foreground">Mínimo: {numberValue(item.min_stock).toLocaleString("pt-BR")} {item.unit}</p></div><strong className="shrink-0 text-sm tabular-nums text-amber-700">{numberValue(item.current_stock).toLocaleString("pt-BR")} {item.unit}</strong></Link>)}</div>}</section></div>
      </div>
    </>}
  </div>;
}
