import { DeleteRecordDialog, type DeleteTarget } from "@/components/shared/DeleteRecordDialog";
import { CommercialPdfButton } from "@/components/comercial/CommercialPdfButton";
import { quoteDocument } from "@/lib/commercial-document";
import { InstallmentEditor, generateParts, validateParts, type PaymentPart } from "@/components/shared/InstallmentEditor";
import { localDate } from "@/lib/finance";
import { useMemo, useRef, useState, useEffect } from "react";
import { Link, useNavigate, useLocation } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { SupabaseClient } from "@supabase/supabase-js";
import { ArrowRight, Check, Copy, FileText, Loader2, Plus, RefreshCw, Search, Trash2, X } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/hooks/use-toast";
import { allRows } from "@/lib/finance";
import { orderRequest } from "@/lib/sales-order";
import { prepareQuote, quoteCostSummary, quoteSnapshotTimeIssues, quoteMoney, quoteStatus, type QuoteDraftLine, type QuoteItem, type QuoteRow, type QuoteStatus } from "@/lib/sales-quote";
import { QuoteSnapshotSummary } from "@/components/comercial/QuoteSnapshotSummary";
import { ProductMaterialChoice } from "@/components/comercial/ProductMaterialChoice";
import { readMaterialOverrides } from "@/lib/product-material-variant";
import { PageHeader } from "@/components/shared/PageHeader";
import { PartnerDialog } from "@/components/comercial/PartnerDialog";
import { SearchableItemSelect } from "@/components/shared/SearchableItemSelect";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";

type QuotesDatabase = { public: { Tables: {
  sales_quotes: { Row: QuoteRow; Insert: Partial<QuoteRow>; Update: Partial<QuoteRow>; Relationships: [] };
  sales_quote_items: { Row: QuoteItem; Insert: Partial<QuoteItem>; Update: Partial<QuoteItem>; Relationships: [] };
}; Views: Record<string, never>; Functions: Record<string, never>; Enums: Record<string, never>; CompositeTypes: Record<string, never> } };
const db = supabase as unknown as SupabaseClient<QuotesDatabase>;
const rpc = supabase.rpc.bind(supabase) as unknown as (name: string, args: Record<string, unknown>) => PromiseLike<{ data: string | null; error: { message: string } | null }>;
const date = (value?: string | null) => value ? new Date(value.length > 10 ? value : `${value}T12:00:00`).toLocaleDateString("pt-BR") : "Não definido";
const newLine = (): QuoteDraftLine => ({ key: crypto.randomUUID(), product_id: "", description: "", quantity: "1", unit_price: "", notes: "", material_overrides: [] });
const emptyForm = () => ({ customer_id: "", valid_until: "", due_date: "", payment_due_date: localDate(new Date()), shipping: "", discount: "", notes: "" });
const statusClass: Record<QuoteStatus, string> = { draft: "bg-muted text-muted-foreground", issued: "bg-blue-50 text-blue-800", approved: "bg-emerald-50 text-emerald-800", rejected: "bg-red-50 text-red-800" };

export default function Orcamentos() {
  const navigate = useNavigate();
  const location = useLocation(); const receivedPricing = useRef<string | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<DeleteTarget | null>(null);
  const [paymentCount, setPaymentCount] = useState("1"); const [paymentDays, setPaymentDays] = useState(""); const [paymentParts, setPaymentParts] = useState<PaymentPart[]>([]);
  const [customerOpen, setCustomerOpen] = useState(false);
  const { profile } = useAuth(); const tenant = profile?.tenant_id; const { toast } = useToast(); const qc = useQueryClient();
  const [search, setSearch] = useState(""); const [filter, setFilter] = useState("all");
  const [selectedId, setSelectedId] = useState<string | null>(null); const [editingId, setEditingId] = useState<string | null>(null);
  const [formOpen, setFormOpen] = useState(false); const [form, setForm] = useState(emptyForm); const [lines, setLines] = useState<QuoteDraftLine[]>([newLine()]);
  const [revision, setRevision] = useState<number | null>(null); const [rejectOpen, setRejectOpen] = useState(false); const [reason, setReason] = useState(""); const [convertOpen, setConvertOpen] = useState(false);
  const saveRequest = useRef<{ signature: string; id: string } | null>(null); const conversionRequest = useRef<{ signature: string; id: string } | null>(null);
  const quotes = useQuery({ queryKey: ["sales_quotes", tenant], enabled: !!tenant, queryFn: () => allRows((a, b) => db.from("sales_quotes").select("*").eq("tenant_id", tenant!).order("created_at", { ascending: false }).order("id").range(a, b)) });
  const details = useQuery({ queryKey: ["sales_quote_items", tenant, selectedId], enabled: !!tenant && !!selectedId, queryFn: () => allRows((a, b) => db.from("sales_quote_items").select("*").eq("tenant_id", tenant!).eq("quote_id", selectedId!).order("line_index").range(a, b)) });
  const customers = useQuery({ queryKey: ["quote_customers", tenant], enabled: !!tenant, queryFn: () => allRows((a, b) => supabase.from("customers").select("id,name").eq("tenant_id", tenant!).eq("is_active", true).order("name").order("id").range(a, b)) });
  const products = useQuery({ queryKey: ["quote_products", tenant], enabled: !!tenant, queryFn: () => allRows((a, b) => supabase.from("products").select("id,name,sku,sale_price").eq("tenant_id", tenant!).eq("is_active", true).order("name").order("id").range(a, b)) });
  const selected = quotes.data?.find(quote => quote.id === selectedId); const items = details.data ?? [];
  const cost = selected ? quoteCostSummary(items, selected) : null;
  const timeIssues = selected?.status === "draft" ? [...new Set(items.flatMap(item => quoteSnapshotTimeIssues(item.product_snapshot)))] : [];
  const filtered = (quotes.data ?? []).filter(quote => (filter === "all" || quote.status === filter) && `${quote.code} ${quote.customer_snapshot?.name || ""}`.toLocaleLowerCase("pt-BR").includes(search.toLocaleLowerCase("pt-BR")));
  const calculation = useMemo(() => { try { return { value: prepareQuote(lines, form.shipping, form.discount), error: null }; } catch (error) { return { value: null, error: (error as Error).message }; } }, [lines, form.shipping, form.discount]);
  const refresh = async () => { await Promise.all([qc.invalidateQueries({ queryKey: ["sales_quotes", tenant] }), qc.invalidateQueries({ queryKey: ["sales_quote_items", tenant] }), qc.invalidateQueries({ queryKey: ["orders"] }), qc.invalidateQueries({ queryKey: ["accounts_receivable"] })]); };
  const failed = (error: Error) => toast({ title: "Não foi possível concluir", description: error.message, variant: "destructive" });
  const save = useMutation({ mutationFn: async () => {
    const prepared = prepareQuote(lines, form.shipping, form.discount);
    const payment_schedule = prepared.total != null && prepared.total > 0 ? validateParts(paymentParts.length ? paymentParts : generateParts(prepared.total, Number(paymentCount), form.payment_due_date, paymentDays), prepared.total) : [];
    const payload = { p_quote_id: editingId, p_quote: { ...form, payment_schedule, customer_id: form.customer_id || null, shipping: prepared.shipping, discount: prepared.discount, total: prepared.total, expected_revision: revision }, p_items: prepared.items };
    saveRequest.current = orderRequest(saveRequest.current, JSON.stringify(payload));
    const result = await rpc("save_sales_quote", { ...payload, p_request_id: saveRequest.current.id }); if (result.error) throw new Error(result.error.message); if (!result.data) throw new Error("O salvamento não foi confirmado. Atualize antes de tentar novamente."); return result.data;
  }, onSuccess: async id => { await refresh(); setFormOpen(false); setSelectedId(id); toast({ title: "Rascunho salvo", description: "Dados comerciais e itens registrados." }); }, onError: failed });
  const transition = useMutation({ mutationFn: async (status: QuoteStatus) => {
    if (!selectedId) throw new Error("Selecione o orçamento."); const result = await rpc("transition_sales_quote", { p_quote_id: selectedId, p_status: status, p_reason: status === "rejected" ? reason.trim() : null });
    if (result.error) throw new Error(result.error.message); if (!result.data) throw new Error("A alteração não foi confirmada.");
  }, onSuccess: async () => { setRejectOpen(false); setReason(""); await refresh(); toast({ title: "Orçamento atualizado" }); }, onError: failed });
  const convert = useMutation({ mutationFn: async () => {
    if (!selectedId) throw new Error("Selecione o orçamento."); conversionRequest.current = orderRequest(conversionRequest.current, selectedId);
    const result = await rpc("convert_sales_quote", { p_quote_id: selectedId, p_request_id: conversionRequest.current.id }); if (result.error) throw new Error(result.error.message); if (!result.data) throw new Error("A venda não foi confirmada. Atualize antes de repetir."); return result.data;
  }, onSuccess: async () => { setConvertOpen(false); await refresh(); toast({ title: "Venda criada", description: "Pedido aprovado e conta a receber registrados. Os itens e a composição da proposta foram preservados." }); }, onError: failed });
  const productionRequest = useRef<{ signature: string; id: string } | null>(null);
  const produce = useMutation({ mutationFn: async () => {
    if (!selectedId) throw new Error("Selecione o orçamento.");
    productionRequest.current = orderRequest(productionRequest.current, selectedId);
    const result = await rpc("request_production_order", { p_quote_id: selectedId, p_order_id: null, p_request_id: productionRequest.current.id });
    if (result.error) throw new Error(result.error.message); if (!result.data) throw new Error("A ordem de produção não foi confirmada."); return result.data;
  }, onSuccess: async id => { await qc.invalidateQueries({ queryKey: ["production_orders"] }); navigate(`/producao/ordens?op=${id}`); }, onError: failed });
  const busy = save.isPending || transition.isPending || convert.isPending || produce.isPending;
  const openNew = () => { setEditingId(null); setRevision(null); setForm(emptyForm()); setPaymentCount("1"); setPaymentDays(""); setPaymentParts([]); setLines([newLine()]); saveRequest.current = null; setFormOpen(true); };
  useEffect(() => {
    if (receivedPricing.current === location.key || !products.data) return;
    const draft = location.state?.pricingQuote;
    const product = products.data.find(p => p.id === draft?.product_id);
    if (!product || !Number.isInteger(draft.quantity) || draft.quantity < 1 || draft.quantity > 10000 || !Number.isFinite(draft.unit_price) || draft.unit_price < 0) return;
    receivedPricing.current = location.key; openNew();
    setLines([{ ...newLine(), product_id: product.id, description: product.name, quantity: String(draft.quantity), unit_price: String(draft.unit_price) }]);
    navigate(location.pathname, { replace: true, state: null });
  }, [location.key, products.data]);
  const edit = (duplicate = false) => {
    if (!selected || details.isLoading || details.error) return;
    let restored: QuoteDraftLine[];
    try { restored = items.map(item => ({ key: crypto.randomUUID(), product_id: item.product_id, description: item.description, quantity: String(item.quantity), unit_price: item.unit_price == null ? "" : String(item.unit_price), notes: item.notes || "", material_overrides: readMaterialOverrides(item.material_overrides) })); }
    catch (error) { failed(error as Error); return; }
    setEditingId(duplicate ? null : selected.id); setRevision(duplicate ? null : selected.revision); saveRequest.current = null;
    setForm({ customer_id: selected.customer_id || "", valid_until: selected.valid_until || "", due_date: selected.due_date || "", payment_due_date: selected.payment_due_date || localDate(new Date()), shipping: String(selected.shipping), discount: String(selected.discount), notes: selected.notes || "" });
    setPaymentCount(String(selected.payment_schedule?.length || 1)); setPaymentDays(""); setPaymentParts((selected.payment_schedule || []).map(p => ({amount: String(p.amount), due_date: p.due_date})));
    setLines(restored); setFormOpen(true);
  };
  const changeLine = (key: string, update: Partial<QuoteDraftLine>) => setLines(current => current.map(line => line.key === key ? { ...line, ...update, ...(update.product_id !== undefined && update.product_id !== line.product_id ? { material_overrides: [] } : {}) } : line));

  return <div className="space-y-5 min-w-0">
    <PageHeader title="Orçamentos" description="Propostas comerciais que podem gerar vendas e ordens de produção." breadcrumbs={[{ label: "Comercial" }, { label: "Orçamentos" }]} actions={<Button onClick={openNew} disabled={busy}><Plus className="mr-2 h-4 w-4" />Novo orçamento</Button>} />
    <div className="grid gap-3 rounded-xl border bg-card p-4 sm:grid-cols-[1fr_180px_auto]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input aria-label="Buscar orçamento" className="pl-9" placeholder="Código ou cliente" value={search} onChange={event => setSearch(event.target.value)} /></div><select aria-label="Filtrar status" className="h-10 min-w-0 rounded-md border bg-background px-3 text-sm" value={filter} onChange={event => setFilter(event.target.value)}><option value="all">Todos os status</option>{Object.entries(quoteStatus).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><Button variant="outline" onClick={() => quotes.refetch()}><RefreshCw className="mr-2 h-4 w-4" />Atualizar</Button></div>
    {quotes.error ? <p role="alert" className="rounded-xl border border-destructive/30 p-5 text-sm text-destructive">Falha ao carregar orçamentos. {quotes.error.message}</p> : quotes.isLoading ? <p className="flex items-center justify-center gap-2 p-12"><Loader2 className="h-5 w-5 animate-spin" />Carregando propostas…</p> : !filtered.length ? <div className="rounded-xl border bg-card p-10 text-center"><FileText className="mx-auto h-9 w-9 text-muted-foreground" /><p className="mt-3 font-medium">Nenhum orçamento encontrado</p><p className="mt-1 text-sm text-muted-foreground">Adicione produtos cadastrados para preparar sua primeira proposta.</p></div> : <div className="overflow-x-auto rounded-lg border bg-card"><table className="w-full text-left text-sm"><thead className="border-b bg-muted/40"><tr>{["Número", "Cliente", "Data", "Situação", "Valor", "Ações"].map(label => <th key={label} className="p-3 font-medium">{label}</th>)}</tr></thead><tbody>{filtered.map(quote => <tr key={quote.id} className="border-b last:border-0"><td className="p-3 font-medium">{quote.code}</td><td className="p-3">{quote.customer_snapshot?.name || "Cliente a definir"}</td><td className="p-3">{date(quote.created_at)}</td><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs ${statusClass[quote.status]}`}>{quote.order_id ? "Venda gerada" : quoteStatus[quote.status]}</span></td><td className="p-3 tabular-nums">{quoteMoney(quote.total)}</td><td className="p-2"><Button variant="ghost" aria-label={`Abrir ${quote.code}`} onClick={() => { setSelectedId(quote.id); setRejectOpen(false); setConvertOpen(false); }}>Abrir</Button></td></tr>)}</tbody></table></div>}
    <Dialog open={!!selectedId && !formOpen} onOpenChange={open => { if (!open && !busy) { setSelectedId(null); setRejectOpen(false); setConvertOpen(false); } }}><DialogContent className="flex max-h-[92dvh] w-[96vw] max-w-6xl flex-col gap-0 overflow-hidden p-0 sm:w-full"><DialogHeader className="shrink-0 border-b px-5 py-5 pr-12"><DialogTitle>{selected?.code || "Orçamento"}</DialogTitle><DialogDescription>{selected?.customer_snapshot?.name || "Cliente a definir"} · {selected ? quoteStatus[selected.status] : "Carregando"}</DialogDescription></DialogHeader><div className="min-h-0 flex-1 space-y-5 overflow-y-auto overscroll-contain p-4 sm:p-5">
      {details.isLoading ? <p>Carregando itens e composição…</p> : details.error ? <p role="alert" className="text-sm text-destructive">Não foi possível carregar os itens. {details.error.message}</p> : selected && <>
        <div className="grid grid-cols-2 gap-4 text-sm sm:grid-cols-4"><div><p className="text-xs text-muted-foreground">Validade</p>{date(selected.valid_until)}</div><div><p className="text-xs text-muted-foreground">Entrega prevista</p>{date(selected.due_date)}</div><div><p className="text-xs text-muted-foreground">Vencimento</p>{date(selected.payment_due_date)}</div><div><p className="text-xs text-muted-foreground">Total da proposta</p><strong>{quoteMoney(selected.total)}</strong></div></div>
        <div className="space-y-3">{items.map(item => <article key={item.id} className="min-w-0 rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-2"><div className="min-w-0"><p className="break-words font-medium">{item.description}</p><p className="text-xs text-muted-foreground">{item.product_snapshot.product?.sku || "Sem SKU"} · {item.quantity} × {quoteMoney(item.unit_price)}</p></div><strong className="tabular-nums">{quoteMoney(item.total)}</strong></div>{item.notes && <p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground">{item.notes}</p>}<details className="mt-3 border-t pt-3 text-xs"><summary className="cursor-pointer font-medium">Composição e custo {selected.status === "draft" ? "do rascunho" : "preservados na proposta"}</summary><p className="mt-2">Referência por unidade: {quoteMoney(item.estimated_unit_cost)} · Custo dos lotes completos: {quoteMoney(item.estimated_total_cost)} · {(item.product_snapshot.plates || []).length} placas · {(item.product_snapshot.requirements || []).length} materiais na composição</p><p className="mt-1 text-muted-foreground">{item.product_snapshot.complete ? "Composição e previsão de custo conferidas." : "Preparação técnica pendente. Complete na etapa de produção."}</p>{(item.product_snapshot.missing || []).length > 0 && <ul className="mt-2 list-disc space-y-1 pl-4 text-amber-800">{item.product_snapshot.missing!.map((missing, index) => <li key={index}>{missing}</li>)}</ul>}<QuoteSnapshotSummary snapshot={item.product_snapshot} quantity={item.quantity} /><Link to="/comercial/produtos" className="mt-2 inline-block underline">Abrir cadastro de produtos</Link></details></article>)}</div>
        <div className="rounded-xl bg-muted/40 p-4 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{quoteMoney(selected.subtotal)}</span></div><div className="mt-2 flex justify-between"><span>Desconto</span><span>{quoteMoney(selected.discount)}</span></div><div className="mt-2 flex justify-between"><span>Frete cobrado</span><span>{quoteMoney(selected.shipping)}</span></div><div className="mt-3 flex justify-between border-t pt-3 text-base font-semibold"><span>Total</span><span>{quoteMoney(selected.total)}</span></div></div>
        <div className="rounded-xl border p-4"><p className="text-sm font-semibold">Previsão interna</p>{cost?.incomplete ? <p role="status" className="mt-2 text-sm text-amber-800">Custo ainda não informado. Você pode emitir a proposta com o preço definido; a preparação técnica será conferida na ordem de produção.</p> : <div className="mt-3 grid gap-3 text-sm sm:grid-cols-3"><div><p className="text-xs text-muted-foreground">Custo dos produtos</p>{quoteMoney(cost?.cost)}</div><div><p className="text-xs text-muted-foreground">Resultado previsto</p>{quoteMoney(cost?.result)}</div><div><p className="text-xs text-muted-foreground">Margem prevista</p>{cost?.margin == null ? "Pendente" : `${cost.margin.toLocaleString("pt-BR", { maximumFractionDigits: 1 })}%`}</div></div>}<p className="mt-3 text-xs text-muted-foreground">Previsão dos lotes completos necessários, incluindo peças extras pela capacidade das placas, após desconto e sem considerar receita ou despesa de frete, tributos e despesas financeiras. Os custos efetivos serão apurados na produção.</p></div>
        {!cost?.incomplete && timeIssues.length > 0 && <div role="status" className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><p className="font-medium">Pendências para a etapa de produção</p><ul className="mt-2 list-disc space-y-1 pl-4">{timeIssues.map(issue => <li key={issue}>{issue}</li>)}</ul></div>}{selected.notes && <p className="whitespace-pre-wrap text-sm">{selected.notes}</p>}{selected.rejection_reason && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-800">Motivo da rejeição: {selected.rejection_reason}</p>}
        {selected.order_id && <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm"><p className="font-medium">Venda criada com a proposta aprovada</p><p className="mt-1">O pedido e a conta a receber mantêm os valores desta versão.</p><Button asChild size="sm" className="mt-3"><Link to={`/comercial/pedidos?pedido=${selected.order_id}`}>Abrir pedido<ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div>}
        {rejectOpen && <div className="rounded-lg border p-4 space-y-3"><Label htmlFor="quote-rejection">Motivo da rejeição</Label><Textarea id="quote-rejection" value={reason} onChange={event => setReason(event.target.value)} disabled={busy} /><Button variant="destructive" disabled={busy || !reason.trim()} onClick={() => transition.mutate("rejected")}>Registrar rejeição</Button></div>}
        {convertOpen && <div className="rounded-lg border border-primary/30 bg-primary/5 p-4 space-y-3"><p className="text-sm font-medium">Converter esta proposta aprovada em venda?</p>{!!selected.payment_schedule?.length && <ul className="list-inside list-disc text-sm">{selected.payment_schedule.map((part, i) => <li key={i}>Parcela {i + 1}: {quoteMoney(part.amount)} · {date(part.due_date)}</li>)}</ul>}<p className="text-sm text-muted-foreground">Serão criados um pedido aprovado e o financeiro a receber de {quoteMoney(selected.total)}, com vencimento em {date(selected.payment_due_date)}. Itens, preços e composição ficarão preservados.</p><div className="flex flex-wrap gap-2"><Button disabled={busy} onClick={() => convert.mutate()}>{convert.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Confirmar venda</Button><Button variant="outline" disabled={busy} onClick={() => setConvertOpen(false)}>Voltar</Button></div></div>}
      </>}
    </div><DialogFooter className="shrink-0 flex-row flex-wrap justify-start gap-2 border-t bg-card p-4 sm:justify-start">{selected && !details.error && !details.isLoading && <><CommercialPdfButton document={quoteDocument(selected, items)} tenantId={tenant} disabled={busy} />{!selected.order_id && ["draft", "rejected"].includes(selected.status) && <Button size="sm" variant="ghost" disabled={busy} onClick={() => setDeleteTarget({ id: selected.id, name: selected.code, kind: "quote" })}><Trash2 className="mr-1.5 h-4 w-4" />Excluir</Button>}<Button size="sm" variant="outline" disabled={busy} onClick={() => edit(true)}><Copy className="mr-1.5 h-4 w-4" />Duplicar</Button>{selected.status === "draft" && <><Button size="sm" variant="outline" disabled={busy} onClick={() => edit()}>Editar</Button><Button size="sm" disabled={busy || selected.total == null} onClick={() => transition.mutate("issued")}><FileText className="mr-1.5 h-4 w-4" />Emitir proposta</Button></>}{selected.status === "issued" && <Button size="sm" disabled={busy} onClick={() => transition.mutate("approved")}><Check className="mr-1.5 h-4 w-4" />Registrar aprovação</Button>}{(selected.status === "draft" || selected.status === "issued") && <Button size="sm" variant="ghost" disabled={busy} onClick={() => { setRejectOpen(!rejectOpen); setConvertOpen(false); }}><X className="mr-1 h-4 w-4" />Rejeitar</Button>}{selected.status === "approved" && !selected.order_id && <Button size="sm" disabled={busy} onClick={() => setConvertOpen(true)}>Converter em venda<ArrowRight className="ml-1.5 h-4 w-4" /></Button>}{selected.status === "approved" && <Button size="sm" variant="outline" disabled={busy} onClick={() => produce.mutate()}>Gerar ordem de produção</Button>}</>}</DialogFooter></DialogContent></Dialog>
    <Dialog open={formOpen} onOpenChange={open => { if (!busy) setFormOpen(open); }}><DialogContent className="flex max-h-[calc(100dvh-1.5rem)] w-[calc(100vw-1.5rem)] max-w-6xl flex-col gap-0 overflow-hidden p-0 sm:p-0"><DialogHeader className="shrink-0 border-b p-4 pr-12 text-left sm:p-5 sm:pr-12"><DialogTitle>{editingId ? "Editar rascunho" : "Novo orçamento"}</DialogTitle><DialogDescription>Selecione os produtos. Preços ausentes permanecem pendentes até a conferência.</DialogDescription></DialogHeader><div className="min-h-0 flex-1 space-y-5 overflow-y-auto overscroll-contain p-4 sm:p-5">
      {(customers.error || products.error) && <p role="alert" className="text-sm text-destructive">Não foi possível carregar clientes ou produtos. Atualize a página antes de continuar.</p>}
      <section aria-label="Cliente e prazos" className="grid min-w-0 grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-[minmax(0,2fr)_minmax(0,1fr)_minmax(0,1fr)]">
        <div className="min-w-0 sm:col-span-2 lg:col-span-1"><Label htmlFor="quote-customer">Cliente</Label><div className="flex flex-wrap items-start gap-2"><div className="min-w-0 flex-1 basis-48"><SearchableItemSelect id="quote-customer" label="Cliente do orçamento" value={form.customer_id} options={(customers.data || []).map(c => ({ id: c.id, label: c.name }))} onChange={id => setForm({ ...form, customer_id: id })} emptyLabel="Selecionar cliente" searchPlaceholder="Digite o nome do cliente…" disabled={busy} /></div><Button type="button" variant="outline" className="min-h-11" disabled={busy} onClick={() => setCustomerOpen(true)}>Cadastrar cliente</Button></div></div>
        {([['valid_until', 'Válido até'], ['due_date', 'Entrega prevista']] as const).map(([name, label]) => <div key={name} className="min-w-0"><Label htmlFor={`quote-${name}`}>{label}</Label><Input id={`quote-${name}`} className="h-11" type="date" value={form[name]} onChange={event => setForm({ ...form, [name]: event.target.value })} disabled={busy} /></div>)}
      </section>
      <section aria-label="Produtos do orçamento" className="space-y-3">
        <div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">Produtos</h3><p className="text-xs text-muted-foreground">Busque por nome ou SKU e informe a quantidade.</p></div>
        {lines.map((line, index) => <article key={line.key} className="min-w-0 space-y-3 rounded-xl border bg-card p-3 sm:p-4">
          <div className="flex items-center justify-between gap-2"><p className="text-xs font-semibold text-muted-foreground">Item {index + 1}</p><Button type="button" size="icon" variant="ghost" className="h-8 w-8" aria-label={`Remover produto ${index + 1}`} disabled={busy || lines.length === 1} onClick={() => setLines(current => current.filter(item => item.key !== line.key))}><Trash2 className="h-4 w-4" /></Button></div>
          <div className="grid min-w-0 grid-cols-2 items-start gap-3 lg:grid-cols-[minmax(0,1fr)_90px_140px_130px]">
            <div className="col-span-2 min-w-0 lg:col-span-1"><Label htmlFor={`quote-product-${line.key}`}>Produto cadastrado</Label><SearchableItemSelect id={`quote-product-${line.key}`} label={`Produto ${index + 1}`} value={line.product_id} options={(products.data || []).map(p => ({ id: p.id, label: `${p.sku ? p.sku + " · " : ""}${p.name}`, description: p.sale_price == null ? "Preço a definir" : quoteMoney(p.sale_price) }))} emptyLabel="Buscar e selecionar produto" searchPlaceholder="Digite nome ou SKU do produto…" disabled={busy} onChange={id => { const product = products.data?.find(p => p.id === id); changeLine(line.key, { product_id: id, description: product?.name || "", unit_price: product?.sale_price == null ? "" : String(product.sale_price) }); }} /></div>
            <div className="min-w-0"><Label htmlFor={`quote-quantity-${line.key}`}>Quantidade</Label><Input id={`quote-quantity-${line.key}`} className="h-11" type="number" min="1" max="500" step="1" value={line.quantity} disabled={busy} onChange={event => changeLine(line.key, { quantity: event.target.value })} /></div>
            <div className="min-w-0"><Label htmlFor={`quote-price-${line.key}`}>Preço unitário (R$)</Label><Input id={`quote-price-${line.key}`} className="h-11" type="number" min="0" step="0.01" placeholder="Pendente" value={line.unit_price} disabled={busy} onChange={event => changeLine(line.key, { unit_price: event.target.value })} /></div>
            <div className="col-span-2 min-w-0 lg:col-span-1"><Label>Subtotal</Label><output className="flex min-h-11 items-center justify-end rounded-md bg-muted px-3 font-semibold tabular-nums">{line.unit_price.trim() && Number.isFinite(Number(line.quantity) * Number(line.unit_price)) ? quoteMoney(Number(line.quantity) * Number(line.unit_price)) : "Pendente"}</output></div>
          </div>
          <div className="grid min-w-0 gap-3 sm:grid-cols-2">
            <div className="min-w-0"><Label htmlFor={`quote-description-${line.key}`}>Descrição para o cliente</Label><Input id={`quote-description-${line.key}`} value={line.description} disabled={busy} onChange={event => changeLine(line.key, { description: event.target.value })} /></div>
            <div className="min-w-0"><Label htmlFor={`quote-notes-${line.key}`}>Observação do item</Label><Input id={`quote-notes-${line.key}`} value={line.notes} disabled={busy} onChange={event => changeLine(line.key, { notes: event.target.value })} /></div>
          </div>
          {line.product_id && <details className="rounded-md border p-3"><summary className="cursor-pointer text-sm">Personalização 3D: material, cor e estimativa</summary><ProductMaterialChoice key={line.product_id} productId={line.product_id} tenantId={tenant} quantity={Number(line.quantity)} unitPrice={line.unit_price.trim() === "" ? null : Number(line.unit_price)} overrides={line.material_overrides ?? []} onChange={value => changeLine(line.key, { material_overrides: value })} onUnitPriceChange={value => changeLine(line.key, { unit_price: String(value) })} disabled={busy} /></details>}
        </article>)}
        <Button type="button" variant="outline" disabled={busy || lines.length >= 500} onClick={() => setLines(current => [...current, newLine()])}><Plus className="mr-2 h-4 w-4" />Adicionar produto</Button>
      </section>
      <div className="grid grid-cols-2 gap-4"><div><Label htmlFor="quote-discount">Desconto (R$)</Label><Input id="quote-discount" type="number" min="0" step="0.01" value={form.discount} disabled={busy} onChange={event => setForm({ ...form, discount: event.target.value })} /></div><div><Label htmlFor="quote-shipping">Frete cobrado (R$)</Label><Input id="quote-shipping" type="number" min="0" step="0.01" value={form.shipping} disabled={busy} onChange={event => setForm({ ...form, shipping: event.target.value })} /></div></div><InstallmentEditor total={calculation.value?.total || 0} firstDate={form.payment_due_date} count={paymentCount} days={paymentDays} parts={paymentParts} onFirstDate={value => setForm(current => ({ ...current, payment_due_date: value }))} onCount={setPaymentCount} onDays={setPaymentDays} onParts={setPaymentParts} disabled={busy} /><div><Label htmlFor="quote-notes">Condições e observações para o cliente</Label><Textarea id="quote-notes" value={form.notes} disabled={busy} onChange={event => setForm({ ...form, notes: event.target.value })} /></div>
      <div className="rounded-xl bg-muted/40 p-4"><div className="flex flex-wrap justify-between gap-2 font-semibold"><span>Total da proposta</span><span>{quoteMoney(calculation.value?.total)}</span></div><p className="mt-2 text-xs text-muted-foreground">Preço e quantidade definem o orçamento. Arquivos, placas e tempos são preparados na ordem de produção.</p>{calculation.error && <p className="mt-2 text-xs text-amber-800">{calculation.error}</p>}</div>
    </div><DialogFooter className="shrink-0 flex-row flex-wrap items-center gap-2 border-t bg-card p-3 sm:p-4"><p className="mr-auto min-w-0 text-sm">Total <strong className="ml-2 tabular-nums">{quoteMoney(calculation.value?.total)}</strong></p><Button variant="outline" disabled={busy} onClick={() => setFormOpen(false)}>Cancelar</Button><Button disabled={busy || !!calculation.error || !!customers.error || !!products.error} onClick={() => save.mutate()}>{save.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Salvar rascunho</Button></DialogFooter></DialogContent></Dialog>
    <DeleteRecordDialog target={deleteTarget} onClose={() => setDeleteTarget(null)} onDeleted={() => setSelectedId(null)} />
    <PartnerDialog kind="customer" open={customerOpen} onClose={() => setCustomerOpen(false)} onSaved={id => setForm(current => ({ ...current, customer_id: id }))} />
  </div>;
}
