import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Eye, Pencil, Plus, Search, Trash2, Archive, RotateCcw } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/hooks/use-toast";
import { allRows } from "@/lib/finance";
import { PartnerDialog, partnerQueryKeys, type Partner, type PartnerKind } from "@/components/comercial/PartnerDialog";
import { PageHeader } from "@/components/shared/PageHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";

export default function Partners({ kind }: { kind: PartnerKind }) {
  const { profile } = useAuth(); const { toast } = useToast(); const qc = useQueryClient();
  const table = kind === "customer" ? "customers" : "vendors"; const title = kind === "customer" ? "Clientes" : "Fornecedores";
  const [search, setSearch] = useState(""); const [status, setStatus] = useState("active");
  const [editing, setEditing] = useState<Partner | null>(null); const [open, setOpen] = useState(false); const [view, setView] = useState<Partner | null>(null); const [deleting, setDeleting] = useState<Partner | null>(null);
  const { data = [], error, isLoading } = useQuery({ queryKey: [table, profile?.tenant_id], enabled: !!profile, queryFn: async () => allRows<Partner>((a, b) => supabase.from(table).select("*").eq("tenant_id", profile!.tenant_id).order("name").order("id").range(a, b) as never) });
  const refresh = () => Promise.all(partnerQueryKeys.map(key => qc.invalidateQueries({ queryKey: [key] })));
  const fail = (e: Error) => toast({ title: "Não foi possível concluir", description: e.message, variant: "destructive" });
  const changeActive = useMutation({ mutationFn: async (row: Partner) => { const result = await supabase.from(table).update({ is_active: !row.is_active }).eq("id", row.id).eq("tenant_id", profile!.tenant_id).eq("updated_at", row.updated_at).select("id").single(); if (result.error) throw result.error; }, onSuccess: async () => { await refresh(); toast({ title: "Situação atualizada" }); }, onError: fail });
  const remove = useMutation({ mutationFn: async () => { if (!deleting) return; const result = await (supabase.rpc.bind(supabase) as unknown as (name: string, args: Record<string, unknown>) => PromiseLike<{ error: { message: string } | null }>)("delete_partner", { p_kind: kind, p_id: deleting.id }); if (result.error) throw new Error(result.error.message); }, onSuccess: async () => { setDeleting(null); await refresh(); toast({ title: "Cadastro excluído" }); }, onError: fail });
  const rows = data.filter(row => (status === "all" || row.is_active === (status === "active")) && [row.name, row.document, row.email, row.phone, row.registration_details?.trade_name].join(" ").toLocaleLowerCase("pt-BR").includes(search.toLocaleLowerCase("pt-BR")));
  return <div className="space-y-5"><PageHeader title={title} description="Cadastros, documentos, endereços e contatos." breadcrumbs={[{ label: "Cadastros" }, { label: title }]} actions={<Button onClick={() => { setEditing(null); setOpen(true); }}><Plus className="mr-2 h-4 w-4" />Adicionar {kind === "customer" ? "cliente" : "fornecedor"}</Button>} />
    <div className="flex flex-wrap gap-3 rounded-lg border bg-card p-4"><div className="relative min-w-56 flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="pl-9" aria-label={`Buscar ${title.toLowerCase()}`} placeholder="Nome, documento, e-mail ou telefone" value={search} onChange={e => setSearch(e.target.value)} /></div><select aria-label="Situação" className="h-10 rounded-md border bg-background px-3 text-sm" value={status} onChange={e => setStatus(e.target.value)}><option value="active">Ativos</option><option value="inactive">Inativos</option><option value="all">Todos</option></select></div>
    {error ? <p role="alert" className="text-destructive">{error.message}</p> : isLoading ? <p>Carregando…</p> : <div className="overflow-x-auto rounded-lg border bg-card"><table className="w-full text-left text-sm"><thead className="border-b bg-muted/40"><tr>{["Nome", "Documento", "Telefone", "E-mail", "Situação", "Ações"].map(label => <th key={label} className="p-3 font-medium">{label}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.id} className="border-b last:border-0"><td className="p-3"><strong className="font-medium">{row.name}</strong>{row.registration_details?.trade_name && <p className="text-xs text-muted-foreground">{row.registration_details.trade_name}</p>}</td><td className="p-3">{row.document || "—"}</td><td className="p-3">{row.phone || "—"}</td><td className="p-3">{row.email || "—"}</td><td className="p-3">{row.is_active ? "Ativo" : "Inativo"}</td><td className="p-2"><div className="flex"><Button size="icon" variant="ghost" aria-label={`Visualizar ${row.name}`} onClick={() => setView(row)}><Eye className="h-4 w-4" /></Button><Button size="icon" variant="ghost" aria-label={`Editar ${row.name}`} onClick={() => { setEditing(row); setOpen(true); }}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" aria-label={`${row.is_active ? "Inativar" : "Reativar"} ${row.name}`} disabled={changeActive.isPending} onClick={() => changeActive.mutate(row)}>{row.is_active ? <Archive className="h-4 w-4" /> : <RotateCcw className="h-4 w-4" />}</Button><Button size="icon" variant="ghost" className="text-destructive" aria-label={`Excluir ${row.name}`} onClick={() => setDeleting(row)}><Trash2 className="h-4 w-4" /></Button></div></td></tr>)}{!rows.length && <tr><td colSpan={6} className="p-10 text-center text-muted-foreground">Nenhum cadastro encontrado.</td></tr>}</tbody></table></div>}
    <PartnerDialog kind={kind} open={open} record={editing} onClose={() => setOpen(false)} />
    <Dialog open={!!view} onOpenChange={value => { if (!value) setView(null); }}><DialogContent className="max-h-[90dvh] max-w-2xl overflow-auto"><DialogHeader><DialogTitle>{view?.name}</DialogTitle><DialogDescription>{view?.document || "Documento não informado"}</DialogDescription></DialogHeader><div className="space-y-3 text-sm"><p>{view?.email || "Sem e-mail"} · {view?.phone || "Sem telefone"}</p>{(view?.registration_details?.addresses || (view?.address ? [view.address] : [])).map((value, i) => { const a = value as Record<string, string>; return <p key={i} className="rounded-md border p-3">{a.type || "Endereço"}: {[a.street, a.number, a.complement, a.neighborhood, a.city, a.state, a.cep].filter(Boolean).join(", ")}</p>; })}{view?.registration_details?.contacts?.map((c, i) => <p key={i}>{[c.name, c.role, c.email, c.phone].filter(Boolean).join(" · ")}</p>)}<p className="whitespace-pre-wrap">{view?.notes}</p></div><DialogFooter><Button onClick={() => { setEditing(view); setView(null); setOpen(true); }}>Editar cadastro</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={!!deleting} onOpenChange={value => { if (!value && !remove.isPending) setDeleting(null); }}><DialogContent><DialogHeader><DialogTitle>Excluir {deleting?.name}?</DialogTitle><DialogDescription>A exclusão é permanente. Cadastros com documentos vinculados podem ser inativados.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" disabled={remove.isPending} onClick={() => setDeleting(null)}>Voltar</Button><Button variant="destructive" disabled={remove.isPending} onClick={() => remove.mutate()}>Excluir cadastro</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
